version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: markdown-it
    versions:
    - 12.0.5
