[build]
  publish = "public"
  command = "npm run build"

  [[redirects]]
    from = "/feed/"
    to = "/feed/feed.xml"
    status = 200

[dev]
  command = "npm start"

[build.environment]
  NODE_VERSION = "22"